"""add_update_timestamp

Revision ID: 008
Revises: 007
Create Date: 2026-06-30 11:52:32.896942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "008"
down_revision = "007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('recovery_phrase_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_phrase_updated_at')
    op.drop_column('users', 'password_updated_at')
    # ### end Alembic commands ###
