"""add_uuid_to_all_tables

Revision ID: 009
Revises: 008
Create Date: 2026-06-30 12:09:28.655918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "009"
down_revision = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_cards_uuid'), 'cards', ['uuid'], unique=True)
    op.add_column('expense_installment_payments', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_expense_installment_payments_uuid'), 'expense_installment_payments', ['uuid'], unique=True)
    op.add_column('expenses', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_expenses_uuid'), 'expenses', ['uuid'], unique=True)
    op.add_column('goal_options', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_goal_options_uuid'), 'goal_options', ['uuid'], unique=True)
    op.add_column('goals', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_goals_uuid'), 'goals', ['uuid'], unique=True)
    op.add_column('user_categories', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_user_categories_uuid'), 'user_categories', ['uuid'], unique=True)
    op.add_column('user_financial_profiles', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_user_financial_profiles_uuid'), 'user_financial_profiles', ['uuid'], unique=True)
    op.add_column('users', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)

    # Enable RLS on all tables
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE user_financial_profiles ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE expense_installment_payments ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE cards ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE user_categories ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE goals ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE goal_options ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE alembic_version ENABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Disable RLS on all tables
    op.execute("ALTER TABLE alembic_version DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE goal_options DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE goals DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE user_categories DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE cards DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE expense_installment_payments DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE user_financial_profiles DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'uuid')
    op.drop_index(op.f('ix_user_financial_profiles_uuid'), table_name='user_financial_profiles')
    op.drop_column('user_financial_profiles', 'uuid')
    op.drop_index(op.f('ix_user_categories_uuid'), table_name='user_categories')
    op.drop_column('user_categories', 'uuid')
    op.drop_index(op.f('ix_goals_uuid'), table_name='goals')
    op.drop_column('goals', 'uuid')
    op.drop_index(op.f('ix_goal_options_uuid'), table_name='goal_options')
    op.drop_column('goal_options', 'uuid')
    op.drop_index(op.f('ix_expenses_uuid'), table_name='expenses')
    op.drop_column('expenses', 'uuid')
    op.drop_index(op.f('ix_expense_installment_payments_uuid'), table_name='expense_installment_payments')
    op.drop_column('expense_installment_payments', 'uuid')
    op.drop_index(op.f('ix_cards_uuid'), table_name='cards')
    op.drop_column('cards', 'uuid')
    # ### end Alembic commands ###
